# Generated by Django 2.1.2 on 2018-10-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_chore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='user',
        ),
    ]
